# Generated by Django 6.0.7 on 2026-07-17 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField(unique=True)),
                ('repo_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('forks', models.PositiveIntegerField(default=0)),
                ('html_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
