# Generated by Django 6.0.7 on 2026-08-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['-stars', '-updated_at_github']},
        ),
        migrations.AddField(
            model_name='repository',
            name='created_at_github',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='default_branch',
            field=models.CharField(blank=True, default='main', max_length=100),
        ),
        migrations.AddField(
            model_name='repository',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repository',
            name='is_fork',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repository',
            name='license',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='repository',
            name='open_issues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='pushed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='repository',
            name='updated_at_github',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='watchers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
